version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
  app:
    depends_on:
      - mongodb
    build:
      context: .
    restart: unless-stopped
    env_file: 
      - path: ./.env
        required: true 
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=$MONGODB_URI
      - MONGODB_NAME=$MONGODB_NAME
      - USER_JWT=$USER_JWT
      - ADMIN_JWT=$ADMIN_JWT
      - NODE_ENV=development
    volumes:
      - '.:/app'
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  dbdata:
  node_modules:  
